### ISSUE TITLE
Node response timeout error thrown as unhandled promise rejection.

### ISSUE THREAD

**Issue by RoboPhred** [zwave-js/zwave-js#1101]
I have a finicky device that doesn't seem to be responding to level changes.  Whenever the library times out trying to communicate to it, the entire program crashes with an unhandled error:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ZWaveError: Timed out while waiting for a response from the node
    at Object.sendDataErrorToZWaveError (D:\dev\git\RoboPhred\wutwot\node_modules\zwave-js\src\lib\driver\StateMachineShared.ts:134:11)
    at D:\dev\git\RoboPhred\wutwot\node_modules\zwave-js\src\lib\driver\SendThreadMachine.ts:421:4
    at D:\dev\git\RoboPhred\wutwot\node_modules\xstate\lib\utils.js:409:33
    at Array.reduce (<anonymous>)
    at Object.updateContext (D:\dev\git\RoboPhred\wutwot\node_modules\xstate\lib\utils.js:399:25)
    at Object.resolveActions (D:\dev\git\RoboPhred\wutwot\node_modules\xstate\lib\actions.js:405:19)
    at StateNode.resolveTransition (D:\dev\git\RoboPhred\wutwot\node_modules\xstate\lib\StateNode.js:787:35)
    at StateNode.transition (D:\dev\git\RoboPhred\wutwot\node_modules\xstate\lib\StateNode.js:733:21)
    at D:\dev\git\RoboPhred\wutwot\node_modules\xstate\lib\interpreter.js:600:34
    at Object.exports.provide (D:\dev\git\RoboPhred\wutwot\node_modules\xstate\lib\serviceScope.js:11:18)
```

I have a handler set up for driver.on("error"), and it does not receive this error.

**Comment by RoboPhred** [comment]
Solved the issue.  I was expecting the error to come through the driver error handler, but it more sensibly comes from a promise returned by setValue
