### ISSUE TITLE
Crash: UnhandledPromiseRejectionWarning: Error: The inclusion could not be started.

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#167]
```
    at ZWaveController.handleAddNodeRequest (C:\Repositories\node-zwave-js\src\lib\controller\Controller.ts:517:7)
    at Driver.handleRequest (C:\Repositories\node-zwave-js\src\lib\driver\Driver.ts:939:33)
    at Driver.handleMessage (C:\Repositories\node-zwave-js\src\lib\driver\Driver.ts:719:15)
    at Driver.serialport_onData (C:\Repositories\node-zwave-js\src\lib\driver\Driver.ts:596:24)
```

**Comment by AlCalzone** [comment]
This is the promise returned by `Driver.beginInclusion()` - it does exactly what it should do.
