### ISSUE TITLE
Crash ZWaveError: Node 14 (endpoint 1) does not support the Command Class Clock!

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwave-js#1704]
**Describe the bug**
```
zwavejs2mqtt    | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zwavejs2mqtt    | ZWaveError: Node 14 (endpoint 1) does not support the Command Class Clock!
zwavejs2mqtt    |     at Object.get (/usr/src/app/node_modules/zwave-js/src/lib/node/Endpoint.ts:268:12)
zwavejs2mqtt    |     at ZWaveNode.handleClockReport (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:2421:34)
zwavejs2mqtt    |     at ZWaveNode.handleCommand (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:1776:16)
zwavejs2mqtt    |     at Driver.handleRequest (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1862:16)
zwavejs2mqtt    |     at Driver.handleUnsolicitedMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1638:16)
zwavejs2mqtt    |     at Object.notifyUnsolicited (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:487:16)
zwavejs2mqtt    |     at notifyUnsolicited (/usr/src/app/node_modules/zwave-js/src/lib/driver/SendThreadMachine.ts:564:19)
zwavejs2mqtt    |     at Interpreter.exec (/usr/src/app/node_modules/xstate/lib/interpreter.js:653:24)
zwavejs2mqtt    |     at Interpreter.execute (/usr/src/app/node_modules/xstate/lib/interpreter.js:206:22)
zwavejs2mqtt    |     at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:226:18)
zwavejs2mqtt    |     at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
zwavejs2mqtt    |     at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
zwavejs2mqtt    |     at Scheduler.flushEvents (/usr/src/app/node_modules/xstate/lib/scheduler.js:53:18)
zwavejs2mqtt    |     at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:45:14)
zwavejs2mqtt    |     at Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)
zwavejs2mqtt    |     at Driver.serialport_onData (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1411:20)
zwavejs2mqtt    | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zwavejs2mqtt    | ZWaveError: Node 14 (endpoint 1) does not support the Command Class Clock!
zwavejs2mqtt    |     at Object.get (/usr/src/app/node_modules/zwave-js/src/lib/node/Endpoint.ts:268:12)
zwavejs2mqtt    |     at ZWaveNode.handleClockReport (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:2421:34)
zwavejs2mqtt    |     at ZWaveNode.handleCommand (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:1776:16)
zwavejs2mqtt    |     at Driver.handleRequest (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1862:16)
zwavejs2mqtt    |     at Driver.handleUnsolicitedMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1638:16)
zwavejs2mqtt    |     at Object.notifyUnsolicited (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:487:16)
zwavejs2mqtt    |     at notifyUnsolicited (/usr/src/app/node_modules/zwave-js/src/lib/driver/SendThreadMachine.ts:564:19)
zwavejs2mqtt    |     at Interpreter.exec (/usr/src/app/node_modules/xstate/lib/interpreter.js:653:24)
zwavejs2mqtt    |     at Interpreter.execute (/usr/src/app/node_modules/xstate/lib/interpreter.js:206:22)
zwavejs2mqtt    |     at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:226:18)
zwavejs2mqtt    |     at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
zwavejs2mqtt    |     at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
zwavejs2mqtt    |     at Scheduler.flushEvents (/usr/src/app/node_modules/xstate/lib/scheduler.js:53:18)
zwavejs2mqtt    |     at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:45:14)
zwavejs2mqtt    |     at Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)
zwavejs2mqtt    |     at Driver.serialport_onData (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1411:20)```

**Device information**

Seems to be Node 14 which is an unknow device.
It is  a aeotec series 7 smart switch

**Last Known Working Configuration**
- [X] New device
- [ ] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version?
    - Have you made any recent configuration changes to the device? Describe.

- [ ] Previously working device (other platform)
    - Which platform?
    - Have you made any recent configuration changes to the device? Describe.
    
**Installation information**
How did you install `node-zwave-js`?
- [ ] `zwavejs2mqtt` (latest) docker image
- [X] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: <!-- fill in -->
    - `zwavejs2mqtt` branch: <!-- fill in -->
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: <!-- Please describe: -->

**To Reproduce**
Steps to reproduce the behavior:
no steps, i did nothing explicit to make this happen

**Additional context**
Add any other context about the problem here.

**Logfile:**
<!--
  ATTACH(!) `zwave-js` logfile with DEBUG or VERBOSE loglevel here. Please no links or gists or embedded logs.
  Please make sure to upload the correct log. If you're unsure, the correct one is called `zwave-<number>.log` and starts with

  ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝

-->

**Comment by scyto** [comment]
full store, sorry the logs are large on debug level
[zwavejs2mqtt-store (6).zip](https://github.com/zwave-js/node-zwave-js/files/5961889/zwavejs2mqtt-store.6.zip)
