### ISSUE TITLE
Error on startup, ZWaveError: Cannot translate a value ID for the non-implemented CC unknown (0x-1)

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js#2289]
**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

Upon starting Z-Wave JS v7.2.0 for the first time, I saw an error on the console and the application stopped.

```
2021-04-09T17:48:18.037850028Z This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-04-09T17:48:18.039558931Z ZWaveError: Cannot translate a value ID for the non-implemented CC unknown (0x-1)
2021-04-09T17:48:18.039747004Z     at ZWaveNode.translateValueID (/app/node_modules/zwave-js/src/lib/node/Node.ts:265:10)
2021-04-09T17:48:18.039807889Z     at ZWaveNode.translateValueEvent (/app/node_modules/zwave-js/src/lib/node/Node.ts:297:23)
2021-04-09T17:48:18.039851483Z     at ValueDB.emit (events.js:315:20)
2021-04-09T17:48:18.039890389Z     at ValueDB.EventEmitter.emit (domain.js:467:12)
2021-04-09T17:48:18.039928566Z     at ValueDB.setValue (/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:248:10)
2021-04-09T17:48:18.039968253Z     at ZWaveNode.set hasSUCReturnRoute [as hasSUCReturnRoute] (/app/node_modules/zwave-js/src/lib/node/Node.ts:584:16)
2021-04-09T17:48:18.040007316Z     at /app/node_modules/zwave-js/src/lib/driver/Driver.ts:924:29
```

**Device information**

Which device(s) is/are affected (make/model)?  N/A?
What are the node IDs? N/A

**Did you change anything?**
- [X] **Yes**: *(please describe)* Upgraded to 7.2.0
- [ ] **No**

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [ ] **No**, it never worked anywhere
- [X] **Yes**, in: *(specify application with versions)* 7.0.0
    
**How are you using `node-zwave-js`**
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [ ] `HomeAssistant` version XYZ
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] `node-red-contrib-zwave-js`
    - Module version (double click node): 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [X] Other:  I have a custom docker image that installs zwave-js-server and zwave-js from NPM. Currently for this it uses zwave-js 7.2.0 and server 1.4.0.

**To Reproduce**

1. Start from a version < 7.2.0 (use a clean cache)
2. Stop zwave-js and restart with 7.2.0.
3. Observe error
4. Restart zwave-js, no error
5. Stop zwave-js and delete the `hasSUCReturnRoute` property from the cache. Restart and go back to step 3.

**Additional context**

**Logfile:**
Log:  [zwave.log](https://github.com/zwave-js/node-zwave-js/files/6287664/zwave.log)

I can provide my pre-upgrade cache files if you want, but it's pretty easy to reproduce by removing the new entry.

**Comment by AlCalzone** [comment]
I know where it is coming from. Didn't happen for me during tests though, need to investigate.
