### ISSUE TITLE
Errors not always returned?

### ISSUE THREAD

**Issue by cgarwood** [zwave-js/zwave-js#3014]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Noticed this while working on the heal node UI in HA by passing an invalid node ID... The first time I try I get the following error in the logs as expected:
```
2021-07-13 23:30:38.140 ERROR ZWAVE-SERVER: Z-Wave error Node 99 was not found!
ZWaveError: Node 99 was not found!
at Map.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:234:11)
at ZWaveController.healNode (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:1668:27)
at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:35:57)
at Object.controller (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:35:103)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:91:99)
at WebSocket.<anonymous> (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:44:45)
at WebSocket.emit (node:events:394:28)
at WebSocket.emit (node:domain:470:12)
at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:835:20)
at Receiver.emit (node:events:394:28)
```

However, subsequent attempts to call heal node with an invalid node ID don't generate any errors in the logs (and as such, zwave-js-server doesn't return the error message back to Home Assistant).

Upon restarting the driver, the error will be returned again the first time.

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

`node-zwave-js`: 7.10.1
`zwavejs2mqtt`: 5.2.1

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

Nothing shows up in the standard zwave-js driver log for either attempt.

**Comment by AlCalzone** [comment]
That looks like the driver is stuck healing.
